name: Docker Hub BE

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '0 13 * * *' 
  workflow_dispatch:

jobs:
  dockerhub:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_JHOSS }}
          password: ${{ secrets.DOCKERHUB_TOKEN_JHOSS }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME_JHOSS }}/as241s5_aej_28-fe:latest
            ${{ secrets.DOCKERHUB_USERNAME_JHOSS }}/as241s5_aej_28-fe:${{ github.sha }}